version: "3.7"
services:
  db:
    image: postgres:14
    ports:
      - "5434:5434"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=peerid
    volumes:
      - "/var/docker_volumes/peerid:/var/lib/postgresql/data"
